#
# define the commands that run vasp_std, vasp_ncl, and vasp_gam
#
nranks=4
nthrds=1

mpi="-np $nranks --map-by node:PE=$nthrds --bind-to core -x OMP_NUM_THREADS=$nthrds --allow-run-as-root --mca btl_sm_backing_directory /tmp"

# For the GNU or NVIDIA OpenMP runtime (gomp/nvomp)
omp="-x OMP_STACKSIZE=512m -x OMP_PLACES=cores -x OMP_PROC_BIND=close"

### For the Intel OpenMP runtime (iomp5)
##omp="-x KMP_AFFINITY=verbose,granularity=fine,compact,1,0 -x KMP_STACKSIZE=512m"

mpirun="/opt/spack-view/bin/mpirun"

export VASP_TESTSUITE_EXE_STD="$mpirun $mpi $omp /opt/spack-view/bin/vasp_std"
export VASP_TESTSUITE_EXE_NCL="$mpirun $mpi $omp /opt/spack-view/bin/vasp_ncl"
export VASP_TESTSUITE_EXE_GAM="$mpirun $mpi $omp /opt/spack-view/bin/vasp_gam"

export VASP_TESTSUITE_SKIP_WAN90=Y
export VASP_TESTSUITE_SKIP_ML=Y